root = "."
tmp_dir = "tmp"

[build]
  full_bin = "TAP_ENABLED=true go run ./cmd/server"
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go"]
  kill_delay = "0s"

[log]
  time = false

[misc]
  clean_on_exit = true
