extensions:
  health_check:
    endpoint: 0.0.0.0:13133
receivers:
  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu: null
      memory: null
      disk: null
      filesystem: null
      network: null
      load: null
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 60s
          static_configs:
            - targets:
                - 0.0.0.0:8888
exporters:
  debug:
    verbosity: detailed
  otlp/signal-studio:
    endpoint: localhost:5317
    retry_on_failure:
      enabled: true
      max_elapsed_time: 300s
    sending_queue:
      enabled: true
      queue_size: 5000
    tls:
      insecure: true
service:
  pipelines:
    metrics:
      receivers:
        - hostmetrics
        - prometheus
      processors:
        - memory_limiter
        - filter
        - batch
      exporters:
        - debug
        - otlp
  extensions:
    - health_check
  telemetry:
    metrics:
      level: normal
processors:
  batch:
    timeout: 5s
    send_batch_size: 512
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128
  filter:
    error_mode: ignore
    metrics:
      exclude:
        match_type: regexp
        metric_names:
          - otelcol_.*
          - promhttp.*
          - scrape_.*
