// Command docgen generates docs/rules.md, docs/api.md, and the Configuration
// section of README.md from Go source metadata.
//
//	go run ./cmd/docgen -rules ../docs/rules.md -api ../docs/api.md -readme ../README.md
package main

import (
	"flag"
	"fmt"
	"os"
	"regexp"
	"strings"

	"github.com/canonical/signal-studio/internal/api"
	"github.com/canonical/signal-studio/internal/rules"
	"github.com/canonical/signal-studio/internal/rules/engine"
	"github.com/canonical/signal-studio/internal/serverconfig"
)

func main() {
	rulesOut := flag.String("rules", "", "output path for rules.md")
	apiOut := flag.String("api", "", "output path for api.md")
	readmePath := flag.String("readme", "", "path to README.md to inject configuration table")
	flag.Parse()

	var failed bool
	if *rulesOut != "" {
		if err := generateRules(*rulesOut); err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			failed = true
		}
	}
	if *apiOut != "" {
		if err := generateAPI(*apiOut); err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			failed = true
		}
	}
	if *readmePath != "" {
		if err := injectReadmeConfig(*readmePath); err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			failed = true
		}
	}
	if failed {
		os.Exit(1)
	}
}

func generateRules(out string) error {
	eng := engine.NewDefaultEngine()

	var staticRules, liveRules, catalogRules []rules.Rule
	for _, r := range eng.Rules() {
		switch r.(type) {
		case rules.CatalogRule:
			catalogRules = append(catalogRules, r)
		case rules.LiveRule:
			liveRules = append(liveRules, r)
		default:
			staticRules = append(staticRules, r)
		}
	}

	var b strings.Builder
	b.WriteString("<!-- Code generated by cmd/docgen; DO NOT EDIT. -->\n\n")
	b.WriteString("# Rules Reference\n\n")

	writeRuleSection(&b, "Static Rules", "Evaluated against your Collector YAML configuration.", staticRules)
	writeRuleSection(&b, "Live Rules", "Evaluated in real time against Prometheus metrics scraped from a running Collector.", liveRules)
	writeRuleSection(&b, "Catalog Rules", "Evaluated against metrics discovered through the OTLP sampling tap.", catalogRules)

	b.WriteString("## Alert Coverage\n\n")
	b.WriteString("Evaluates Prometheus alerting rules against your Collector config to detect alerts that reference metrics your pipelines would drop or fail to deliver. See [ADR-0018](adr/0018-alert-rule-coverage-analysis.md) for details.\n")

	if err := os.WriteFile(out, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("writing %s: %w", out, err)
	}
	fmt.Fprintf(os.Stderr, "Generated %s (%d static, %d live, %d catalog rules)\n",
		out, len(staticRules), len(liveRules), len(catalogRules))
	return nil
}

func writeRuleSection(b *strings.Builder, title, description string, rr []rules.Rule) {
	b.WriteString("## " + title + "\n\n")
	b.WriteString(description + "\n\n")
	b.WriteString("| ID | Severity | Description |\n")
	b.WriteString("| -- | -------- | ----------- |\n")
	for _, r := range rr {
		fmt.Fprintf(b, "| `%s` | %s | %s |\n", r.ID(), r.DefaultSeverity(), r.Description())
	}
	b.WriteString("\n")
}

func generateAPI(out string) error {
	var b strings.Builder
	b.WriteString("<!-- Code generated by cmd/docgen; DO NOT EDIT. -->\n\n")
	b.WriteString("# API Reference\n\n")
	b.WriteString("All endpoints are served from the backend HTTP server (default port `8080`).\n\n")

	var currentSection string
	for _, r := range api.Routes {
		if r.Section != currentSection {
			if currentSection != "" {
				b.WriteString("\n")
			}
			b.WriteString("## " + r.Section + "\n\n")
			b.WriteString("| Method | Path | Description |\n")
			b.WriteString("| ------ | ---- | ----------- |\n")
			currentSection = r.Section
		}
		fmt.Fprintf(&b, "| `%s` | `%s` | %s |\n", r.Method, r.Path, r.Description)
	}
	b.WriteString("\n")

	if err := os.WriteFile(out, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("writing %s: %w", out, err)
	}
	fmt.Fprintf(os.Stderr, "Generated %s (%d routes)\n", out, len(api.Routes))
	return nil
}

func injectReadmeConfig(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("reading %s: %w", path, err)
	}

	var b strings.Builder
	b.WriteString("<!-- BEGIN GENERATED:config -->\n")
	b.WriteString("## Configuration\n\n")
	b.WriteString("| Variable | Default | Description |\n")
	b.WriteString("| -------- | ------- | ----------- |\n")
	for _, v := range serverconfig.EnvVars {
		fmt.Fprintf(&b, "| `%s` | `%s` | %s |\n", v.Name, v.Default, v.Description)
	}
	b.WriteString("<!-- END GENERATED:config -->")

	re := regexp.MustCompile(`(?s)<!-- BEGIN GENERATED:config -->.*?<!-- END GENERATED:config -->`)
	if !re.MatchString(string(data)) {
		return fmt.Errorf("markers <!-- BEGIN/END GENERATED:config --> not found in %s", path)
	}
	replaced := re.ReplaceAllString(string(data), b.String())

	if err := os.WriteFile(path, []byte(replaced), 0644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	fmt.Fprintf(os.Stderr, "Injected configuration table into %s (%d vars)\n", path, len(serverconfig.EnvVars))
	return nil
}
